//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_7b.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Record", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((this.RecordIDField.Equals(value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetDictResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        lab_7b.ServiceReference.GetDictResponse GetDict(lab_7b.ServiceReference.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_7b.ServiceReference.GetDictResponse> GetDictAsync(lab_7b.ServiceReference.GetDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetRecordResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecord", ReplyAction="*")]
        lab_7b.ServiceReference.GetRecordResponse GetRecord(lab_7b.ServiceReference.GetRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_7b.ServiceReference.GetRecordResponse> GetRecordAsync(lab_7b.ServiceReference.GetRecordRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем name из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        lab_7b.ServiceReference.AddDictResponse AddDict(lab_7b.ServiceReference.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_7b.ServiceReference.AddDictResponse> AddDictAsync(lab_7b.ServiceReference.AddDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем name из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        lab_7b.ServiceReference.UpdDictResponse UpdDict(lab_7b.ServiceReference.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<lab_7b.ServiceReference.UpdDictResponse> UpdDictAsync(lab_7b.ServiceReference.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        long DelDict(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task<long> DelDictAsync(long id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://tempuri.org/", Order=0)]
        public lab_7b.ServiceReference.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(lab_7b.ServiceReference.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab_7b.ServiceReference.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(lab_7b.ServiceReference.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lab_7b.ServiceReference.Record[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(lab_7b.ServiceReference.Record[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecord", Namespace="http://tempuri.org/", Order=0)]
        public lab_7b.ServiceReference.GetRecordRequestBody Body;
        
        public GetRecordRequest() {
        }
        
        public GetRecordRequest(lab_7b.ServiceReference.GetRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public GetRecordRequestBody() {
        }
        
        public GetRecordRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab_7b.ServiceReference.GetRecordResponseBody Body;
        
        public GetRecordResponse() {
        }
        
        public GetRecordResponse(lab_7b.ServiceReference.GetRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lab_7b.ServiceReference.Record GetRecordResult;
        
        public GetRecordResponseBody() {
        }
        
        public GetRecordResponseBody(lab_7b.ServiceReference.Record GetRecordResult) {
            this.GetRecordResult = GetRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://tempuri.org/", Order=0)]
        public lab_7b.ServiceReference.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(lab_7b.ServiceReference.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(string name, string phone) {
            this.name = name;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab_7b.ServiceReference.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(lab_7b.ServiceReference.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lab_7b.ServiceReference.Record AddDictResult;
        
        public AddDictResponseBody() {
        }
        
        public AddDictResponseBody(lab_7b.ServiceReference.Record AddDictResult) {
            this.AddDictResult = AddDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://tempuri.org/", Order=0)]
        public lab_7b.ServiceReference.UpdDictRequestBody Body;
        
        public UpdDictRequest() {
        }
        
        public UpdDictRequest(lab_7b.ServiceReference.UpdDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long recordID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phone;
        
        public UpdDictRequestBody() {
        }
        
        public UpdDictRequestBody(long recordID, string name, string phone) {
            this.recordID = recordID;
            this.name = name;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab_7b.ServiceReference.UpdDictResponseBody Body;
        
        public UpdDictResponse() {
        }
        
        public UpdDictResponse(lab_7b.ServiceReference.UpdDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lab_7b.ServiceReference.Record UpdDictResult;
        
        public UpdDictResponseBody() {
        }
        
        public UpdDictResponseBody(lab_7b.ServiceReference.Record UpdDictResult) {
            this.UpdDictResult = UpdDictResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : lab_7b.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<lab_7b.ServiceReference.WebServiceSoap>, lab_7b.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_7b.ServiceReference.GetDictResponse lab_7b.ServiceReference.WebServiceSoap.GetDict(lab_7b.ServiceReference.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public lab_7b.ServiceReference.Record[] GetDict() {
            lab_7b.ServiceReference.GetDictRequest inValue = new lab_7b.ServiceReference.GetDictRequest();
            inValue.Body = new lab_7b.ServiceReference.GetDictRequestBody();
            lab_7b.ServiceReference.GetDictResponse retVal = ((lab_7b.ServiceReference.WebServiceSoap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_7b.ServiceReference.GetDictResponse> lab_7b.ServiceReference.WebServiceSoap.GetDictAsync(lab_7b.ServiceReference.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab_7b.ServiceReference.GetDictResponse> GetDictAsync() {
            lab_7b.ServiceReference.GetDictRequest inValue = new lab_7b.ServiceReference.GetDictRequest();
            inValue.Body = new lab_7b.ServiceReference.GetDictRequestBody();
            return ((lab_7b.ServiceReference.WebServiceSoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_7b.ServiceReference.GetRecordResponse lab_7b.ServiceReference.WebServiceSoap.GetRecord(lab_7b.ServiceReference.GetRecordRequest request) {
            return base.Channel.GetRecord(request);
        }
        
        public lab_7b.ServiceReference.Record GetRecord(long id) {
            lab_7b.ServiceReference.GetRecordRequest inValue = new lab_7b.ServiceReference.GetRecordRequest();
            inValue.Body = new lab_7b.ServiceReference.GetRecordRequestBody();
            inValue.Body.id = id;
            lab_7b.ServiceReference.GetRecordResponse retVal = ((lab_7b.ServiceReference.WebServiceSoap)(this)).GetRecord(inValue);
            return retVal.Body.GetRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_7b.ServiceReference.GetRecordResponse> lab_7b.ServiceReference.WebServiceSoap.GetRecordAsync(lab_7b.ServiceReference.GetRecordRequest request) {
            return base.Channel.GetRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab_7b.ServiceReference.GetRecordResponse> GetRecordAsync(long id) {
            lab_7b.ServiceReference.GetRecordRequest inValue = new lab_7b.ServiceReference.GetRecordRequest();
            inValue.Body = new lab_7b.ServiceReference.GetRecordRequestBody();
            inValue.Body.id = id;
            return ((lab_7b.ServiceReference.WebServiceSoap)(this)).GetRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_7b.ServiceReference.AddDictResponse lab_7b.ServiceReference.WebServiceSoap.AddDict(lab_7b.ServiceReference.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public lab_7b.ServiceReference.Record AddDict(string name, string phone) {
            lab_7b.ServiceReference.AddDictRequest inValue = new lab_7b.ServiceReference.AddDictRequest();
            inValue.Body = new lab_7b.ServiceReference.AddDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            lab_7b.ServiceReference.AddDictResponse retVal = ((lab_7b.ServiceReference.WebServiceSoap)(this)).AddDict(inValue);
            return retVal.Body.AddDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_7b.ServiceReference.AddDictResponse> lab_7b.ServiceReference.WebServiceSoap.AddDictAsync(lab_7b.ServiceReference.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab_7b.ServiceReference.AddDictResponse> AddDictAsync(string name, string phone) {
            lab_7b.ServiceReference.AddDictRequest inValue = new lab_7b.ServiceReference.AddDictRequest();
            inValue.Body = new lab_7b.ServiceReference.AddDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            return ((lab_7b.ServiceReference.WebServiceSoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab_7b.ServiceReference.UpdDictResponse lab_7b.ServiceReference.WebServiceSoap.UpdDict(lab_7b.ServiceReference.UpdDictRequest request) {
            return base.Channel.UpdDict(request);
        }
        
        public lab_7b.ServiceReference.Record UpdDict(long recordID, string name, string phone) {
            lab_7b.ServiceReference.UpdDictRequest inValue = new lab_7b.ServiceReference.UpdDictRequest();
            inValue.Body = new lab_7b.ServiceReference.UpdDictRequestBody();
            inValue.Body.recordID = recordID;
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            lab_7b.ServiceReference.UpdDictResponse retVal = ((lab_7b.ServiceReference.WebServiceSoap)(this)).UpdDict(inValue);
            return retVal.Body.UpdDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab_7b.ServiceReference.UpdDictResponse> lab_7b.ServiceReference.WebServiceSoap.UpdDictAsync(lab_7b.ServiceReference.UpdDictRequest request) {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab_7b.ServiceReference.UpdDictResponse> UpdDictAsync(long recordID, string name, string phone) {
            lab_7b.ServiceReference.UpdDictRequest inValue = new lab_7b.ServiceReference.UpdDictRequest();
            inValue.Body = new lab_7b.ServiceReference.UpdDictRequestBody();
            inValue.Body.recordID = recordID;
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            return ((lab_7b.ServiceReference.WebServiceSoap)(this)).UpdDictAsync(inValue);
        }
        
        public long DelDict(long id) {
            return base.Channel.DelDict(id);
        }
        
        public System.Threading.Tasks.Task<long> DelDictAsync(long id) {
            return base.Channel.DelDictAsync(id);
        }
    }
}
